variables:
  - group: secrets

jobs:
  - job: TestMoleculeKit
    displayName: Test MoleculeKit
    pool:    
      vmImage: 'Ubuntu-16.04'

    continueOnError: false
    
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 2

    steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH

    - bash: sudo chown -R $USER /usr/share/miniconda
      displayName: Take ownership of conda installation

    - bash:  conda install -y -q conda-build=3
      displayName: Installing conda-build

    - bash: conda create -y -q --name test python=$(python.version)
      displayName: Create Anaconda test environment

    - bash: |
        python -m pip install --upgrade pip setuptools wheel
        pip install twine codecov coverage
      displayName: Install pip packages

    - bash: './ci/travis/compile_htmdlib.sh'
      displayName: Clone and compile the private htmdlib repo

    - bash: |
        source activate test
        conda install -y -q tqdm ipython matplotlib joblib scikit-learn rdkit mdtraj htmd-pdb2pqr propka openbabel -c acellera  # Installing extra dependencies for tests
      displayName: Install Anaconda packages

    - bash: python ci/travis/insert_placeholder_values.py
      displayName: Insert version number and dependencies into pip and conda recipes

    - bash: |
        source activate test
        python setup.py install
      displayName: Install moleculekit locally

    - bash: |
        source activate test
        coverage run -m unittest discover --start-directory ./moleculekit --pattern "*.py"
      condition: succeededOrFailed()
      displayName: Run tests