strategy:
  matrix:
    ubuntu16:
      containerImage: ubuntu:16.04

container: $[ variables['containerImage'] ]

- job: TestMoleculeKit
  displayName: Test MoleculeKit
  continueOnError: false
  
  strategy:
    parallel: 2
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'
      Python37:
        PYTHON_VERSION: '3.7'

  steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH