parameters:
  name: ''  # defaults for any parameters that aren't specified
  displayName: ''
  vmImage: ''
  OS: ''
  dependsOn: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:    
      vmImage: ${{ parameters.vmImage }}

    dependsOn: ${{ parameters.dependsOn }}

    continueOnError: false
    
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        # Need to wait for numba to support 3.9. Should be done around March 2021 https://github.com/numba/numba/issues/6345 
        # Python39:
        #   python.version: '3.9'
      maxParallel: 4

    variables:
      OS: ${{ parameters.OS }}

    steps:
    - template: templates/conda_config.yml

    - bash:  conda install -y -q conda-build=3
      displayName: Installing conda-build

    - bash: python ci/insert_placeholder_values.py
      displayName: Insert version number and dependencies into pip and conda recipes
      env:
        CONDA_PY: $(python.version)
    
    - ${{ if eq(parameters.OS, 'linux') }}:  # Don't build pypi for OSX. It's platform independent
      - template: templates/build_pypi_artifact.yml
      
    - template: templates/build_conda_artifact.yml

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: moleculekit_$(OS)_$(python.version)