variables:
  - group: secrets

trigger:
  branches:
    include:
      - master
      - azure
      - refs/tags/*

stages:
  # - stage: Test
  #   jobs:
  #     - template: test_job.yml
  #       parameters:
  #         name: TestLinux
  #         displayName: Linux tests
  #         vmImage: 'ubuntu-16.04'
  #         OS: linux

  #     - template: test_job.yml
  #       parameters:
  #         name: TestMacOSX
  #         displayName: Mac OSX tests
  #         vmImage: 'macOS-latest'
  #         OS: mac

  - stage: Build
    # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - template: build_artifact_job.yml
        parameters:
          name: BuildLinuxArtifacts
          displayName: Build Linux Artifacts
          vmImage: 'ubuntu-16.04'
          OS: linux

      - template: build_artifact_job.yml
        parameters:
          name: BuildOSXArtifacts
          displayName: Build OSX Artifacts
          vmImage: 'macOS-latest'
          OS: mac

  - stage: Publish
    # condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: PublishPyPI
        pool:
          vmImage: "ubuntu-16.04"

        steps:
        - script: 'pip install twine'

        - task: TwineAuthenticate@1
          displayName: 'Twine Authenticate'
          inputs:
            pythonUploadServiceConnection: pypi

        - script: |
            python -m twine upload -r pypi --config-file $(PYPIRC_PATH) '$(Build.ArtifactStagingDirectory)/*.whl'
          displayName: 'Uploading to PyPI from $(Build.ArtifactStagingDirectory)'