# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: molstar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='molstar.proto',
  package='molstar',
  syntax='proto3',
  serialized_options=b'\242\002\002SL',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmolstar.proto\x12\x07molstar\"u\n\x0cMoleculeData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tstructure\x18\x02 \x01(\t\x12\x0c\n\x04traj\x18\x03 \x01(\x0c\x12\x0b\n\x03\x62ox\x18\x04 \x03(\x02\x12\x11\n\trepr_type\x18\x05 \x01(\t\x12\x16\n\x0erepr_selection\x18\x06 \x01(\t\"\x1f\n\x0cLoadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\x0eMoleculeLoader\x12>\n\x0cLoadMolecule\x12\x15.molstar.MoleculeData\x1a\x15.molstar.LoadResponse\"\x00\x42\x05\xa2\x02\x02SLb\x06proto3'
)




_MOLECULEDATA = _descriptor.Descriptor(
  name='MoleculeData',
  full_name='molstar.MoleculeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='molstar.MoleculeData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='structure', full_name='molstar.MoleculeData.structure', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traj', full_name='molstar.MoleculeData.traj', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box', full_name='molstar.MoleculeData.box', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repr_type', full_name='molstar.MoleculeData.repr_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repr_selection', full_name='molstar.MoleculeData.repr_selection', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=143,
)


_LOADRESPONSE = _descriptor.Descriptor(
  name='LoadResponse',
  full_name='molstar.LoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='molstar.LoadResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['MoleculeData'] = _MOLECULEDATA
DESCRIPTOR.message_types_by_name['LoadResponse'] = _LOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoleculeData = _reflection.GeneratedProtocolMessageType('MoleculeData', (_message.Message,), {
  'DESCRIPTOR' : _MOLECULEDATA,
  '__module__' : 'molstar_pb2'
  # @@protoc_insertion_point(class_scope:molstar.MoleculeData)
  })
_sym_db.RegisterMessage(MoleculeData)

LoadResponse = _reflection.GeneratedProtocolMessageType('LoadResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOADRESPONSE,
  '__module__' : 'molstar_pb2'
  # @@protoc_insertion_point(class_scope:molstar.LoadResponse)
  })
_sym_db.RegisterMessage(LoadResponse)


DESCRIPTOR._options = None

_MOLECULELOADER = _descriptor.ServiceDescriptor(
  name='MoleculeLoader',
  full_name='molstar.MoleculeLoader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=178,
  serialized_end=258,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadMolecule',
    full_name='molstar.MoleculeLoader.LoadMolecule',
    index=0,
    containing_service=None,
    input_type=_MOLECULEDATA,
    output_type=_LOADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOLECULELOADER)

DESCRIPTOR.services_by_name['MoleculeLoader'] = _MOLECULELOADER

# @@protoc_insertion_point(module_scope)
