package:
  name: moleculekit
  version: BUILD_VERSION_PLACEHOLDER

source:
   path: ../..

build:
  script:
    - "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cython
    - versioneer==0.26
DEPENDENCY_PLACEHOLDER
  run:
    - python
DEPENDENCY_PLACEHOLDER

about:
  home: https://github.com/acellera/moleculekit/
  license: "HTMD Software License version 1.1"
  license_file: LICENSE
  summary: A molecule reading/writing and manipulation package.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - stefdoerr
