package:
  name: moleculekit
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

requirements:
  host:
    - python
DEPENDENCY_PLACEHOLDER
  run:
    - python
DEPENDENCY_PLACEHOLDER

about:
  home: https://github.com/acellera/moleculekit/
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
  summary: A molecule reading/writing and manipulation package.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - stefdoerr
