name: Build docs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install docs deps
        run: uv sync --group docs --group test

      - name: Generate rst docs
        run: cd doc && uv run make rst

      - name: Build HTML
        run: cd doc && uv run sphinx-build -b html source build/html

  publish:
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.ref, 'refs/tags/') }}
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_DOCS }}
          service_account: ${{ secrets.GCP_DOC_SERVICE_ACCOUNT }}

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install docs deps
        run: uv sync --group docs --group test

      - name: Build HTML
        run: cd doc && uv run make html

      - name: Sync HTML to GCP docs bucket
        run: |
          gcloud storage rsync doc/build/html gs://software-acellera-final/moleculekit \
            --recursive \
            --delete-unmatched-destination-objects
