name: Build docs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  makedocs:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_DOCS }}
          service_account: ${{ secrets.GCP_DOC_SERVICE_ACCOUNT }}

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install deps
        run: uv sync --group docs

      - name: Generate rst docs
        run: cd doc && uv run make rst

      - name: Publish to GCP intermediate docs bucket
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "doc/source"
          destination: "software-acellera-intermediate/public_docs/moleculekit/${{ github.ref_name }}"

      - name: Write update file to upload
        run: echo "Updated" > update

      - name: Upload "update" file to trigger new docs
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "update"
          destination: "software-acellera-intermediate/"
