name: Build docs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  makedocs:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_DOCS }}
          service_account: ${{ secrets.GCP_DOC_SERVICE_ACCOUNT }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          channels: acellera,conda-forge,defaults

      - name: Install conda deps
        run: |
          conda install -y -q --file extra_requirements.txt nbconvert sphinx=6.1.3 python=3.9
          pip install pydata-sphinx-theme==0.13.1 sphinx-argparse sphinx-notfound-page sphinx-sitemap
          pip install .
          # pdb2pqr is downgrading docutils for some reason and causes failures
          pip install docutils==0.19

      - name: Generate rst docs
        run: |
          cd doc; make rst

      - name: Publish to GCP intermediate docs bucket
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "doc/source"
          destination: "software-acellera-intermediate/public_docs/moleculekit/${{ github.ref_name }}"

      - name: Write update file to upload
        run: echo "Updated" > update

      - name: Upload "update" file to trigger new docs
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "update"
          destination: "software-acellera-intermediate/"
