name: Test code

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2022"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install blast for OPM tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y ncbi-blast+

      - name: Install blast for OPM tests
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install blast

      - name: Lint with flake8
        run: |
          uvx flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          uvx flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check docstring parameter consistency
        run: uvx --with pydoclint flake8 --config=flake8-docstrings.cfg moleculekit

      - name: Install moleculekit
        run: uv sync --group test

      - name: Test
        run: uv run pytest -n auto ./tests/ --durations=20
        env:
          LOCAL_PDB_REPO: ./tests/pdb/
          SKIP_SPEED_TESTS: True
