name: Whole

on: [push]

jobs:
  test:
    if: ${{ ! startsWith(github.event.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    if: startsWith(github.event.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  publish_conda:
    needs: publish
    if: startsWith(github.event.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish_conda.yml
    secrets: inherit

  publish_pyodide:
    needs: publish
    if: startsWith(github.event.ref, 'refs/tags/v')
    uses: ./.github/workflows/pyodide_build.yml
    secrets: inherit

  docs:
    needs: publish
    if: startsWith(github.event.ref, 'refs/tags/')
    uses: ./.github/workflows/docs.yml
    secrets: inherit

  docs_update:
    if: startsWith(github.event.ref, 'refs/tags/d')
    uses: ./.github/workflows/docs.yml
    secrets: inherit
